### ISSUE TITLE
v1.0.0 roadmap.

### ISSUE THREAD

**Issue by hsblhsn** [hsblhsn/gocialite#1]
- [ ] doc: Update readme.
- [ ] meta: Add linter and other dot-files.
- [ ] testing: Add test cases and target at least 80% coverage.
